# Generated by Django 4.1.2 on 2022-10-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='HospitalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hospital_type',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reservation_status',
            },
        ),
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reservation_type',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'time',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_number', models.UUIDField()),
                ('patient_name', models.CharField(max_length=10)),
                ('patient_birth', models.DateField()),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.hospital')),
                ('reservation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationstatus')),
                ('reservation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationtype')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.time')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.hospitaltype'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.province'),
        ),
    ]
