# Generated by Django 4.1.2 on 2022-10-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_reservation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_available',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
